# Generated by Django 5.1.3 on 2024-11-21 16:27

from django.db import migrations


def add_initial_customers(apps, schema_editor):
    Customer = apps.get_model("app", "Customer")
    Customer.objects.create(name="Alice", email="alice@email.com", age=25)
    Customer.objects.create(name="Bob", email="bob@email.com", age=30)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_customers)
    ]
